project_id = "vltveasdxtfvvqbzxzuf"

[functions.add-courier]
verify_jwt = true

[functions.admin-database-maintenance]
verify_jwt = true

[functions.admin-database-backup]
verify_jwt = true

[functions.courier-app]
verify_jwt = true

[functions.calculate-eta]
verify_jwt = true

[functions.create-order]
verify_jwt = false
